-- Reemplaza el árbol de categorías de la V9 por uno nuevo provisto por el negocio, esta vez
-- de 2 niveles (categoría > subcategoría) en vez de 3. Varias categorías no tienen
-- subcategorías (Accesorios, DESTACADOS, Electrodomésticos, Proyectores, Scanners,
-- Sillas y escritorios, Tablets) y son hoja en sí mismas.
-- Los productos ya se vaciaron antes de esta migración (mismo motivo que la V9: evitar que
-- categoria_id quede apuntando a filas que se van a borrar).
DELETE FROM categorias;

INSERT INTO categorias (id, nombre, padre_id, created_at, updated_at) VALUES
(1, 'Accesorios', NULL, now(), now()),
(2, 'Almacenamiento', NULL, now(), now()),
(3, 'Pen Drive', 2, now(), now()),
(4, 'Tarjetas de memoria', 2, now(), now()),
(5, 'Computadoras', NULL, now(), now()),
(6, 'All in One', 5, now(), now()),
(7, 'Kit PC', 5, now(), now()),
(8, 'Mini PC', 5, now(), now()),
(9, 'PC', 5, now(), now()),
(10, 'Conectividad', NULL, now(), now()),
(11, 'Accesorios Bluetooth', 10, now(), now()),
(12, 'Access Point y Extensores de Rango', 10, now(), now()),
(13, 'Cables', 10, now(), now()),
(14, 'Cámaras IP', 10, now(), now()),
(15, 'Media conv/módulos', 10, now(), now()),
(16, 'Modem ADSL y GPON', 10, now(), now()),
(17, 'Placas de Red Ethernet y Adaptadores USB', 10, now(), now()),
(18, 'Placas de Red WiFi PCI', 10, now(), now()),
(19, 'Placas de Red WiFi USB', 10, now(), now()),
(20, 'POE (Power Over Ethernet)', 10, now(), now()),
(21, 'Router', 10, now(), now()),
(22, 'Router Wireless', 10, now(), now()),
(23, 'Smart Home', 10, now(), now()),
(24, 'Switches Administrables', 10, now(), now()),
(25, 'Switches No Administrables', 10, now(), now()),
(26, 'Consumibles', NULL, now(), now()),
(27, 'Cartuchos', 26, now(), now()),
(28, 'Consumibles HP', 26, now(), now()),
(29, 'Tintas', 26, now(), now()),
(30, 'Coolers', NULL, now(), now()),
(31, 'Fans', 30, now(), now()),
(32, 'Watercoolers', 30, now(), now()),
(33, 'DESTACADOS', NULL, now(), now()),
(34, 'Discos Rígidos / SSD', NULL, now(), now()),
(35, 'Carry Disk', 34, now(), now()),
(36, 'Disco Rígido Externo', 34, now(), now()),
(37, 'Disco Rígido NAS', 34, now(), now()),
(38, 'Disco Rígido Notebook', 34, now(), now()),
(39, 'Disco Rígido SATA', 34, now(), now()),
(40, 'Disco SSD', 34, now(), now()),
(41, 'Disco SSD M2', 34, now(), now()),
(42, 'Electrodomésticos', NULL, now(), now()),
(43, 'Energía', NULL, now(), now()),
(44, 'Estabilizadores', 43, now(), now()),
(45, 'UPS', 43, now(), now()),
(46, 'Gabinetes y Fuentes', NULL, now(), now()),
(47, 'Fuentes de Alimentación', 46, now(), now()),
(48, 'Gabinetes con Fuente', 46, now(), now()),
(49, 'Gabinetes sin Fuente', 46, now(), now()),
(50, 'Kit Gabinete, teclado, mouse y parlante', 46, now(), now()),
(51, 'Impresoras', NULL, now(), now()),
(52, 'Ink Jet', 51, now(), now()),
(53, 'Laser', 51, now(), now()),
(54, 'Multifunción', 51, now(), now()),
(55, 'Memorias RAM', NULL, now(), now()),
(56, 'Memoria DDR2', 55, now(), now()),
(57, 'Memoria DDR3', 55, now(), now()),
(58, 'Memoria DDR4', 55, now(), now()),
(59, 'Memoria DDR5', 55, now(), now()),
(60, 'Memoria Sodimm', 55, now(), now()),
(61, 'Microprocesadores', NULL, now(), now()),
(62, 'AMD', 61, now(), now()),
(63, 'Intel', 61, now(), now()),
(64, 'Monitores', NULL, now(), now()),
(65, 'Monitor Consumo', 64, now(), now()),
(66, 'Monitor Corporativo', 64, now(), now()),
(67, 'Monitor Gamer', 64, now(), now()),
(68, 'Mothers', NULL, now(), now()),
(69, 'Plataforma AMD', 68, now(), now()),
(70, 'Plataforma Intel', 68, now(), now()),
(71, 'Notebooks', NULL, now(), now()),
(72, 'Consumo', 71, now(), now()),
(73, 'Corporativa', 71, now(), now()),
(74, 'Gamer', 71, now(), now()),
(75, 'Periféricos', NULL, now(), now()),
(76, 'Auriculares', 75, now(), now()),
(77, 'Micrófonos', 75, now(), now()),
(78, 'Mouse', 75, now(), now()),
(79, 'Mousepads', 75, now(), now()),
(80, 'Parlantes', 75, now(), now()),
(81, 'Power Banks', 75, now(), now()),
(82, 'Teclado + Mouse', 75, now(), now()),
(83, 'Teclados', 75, now(), now()),
(84, 'Web Cam', 75, now(), now()),
(85, 'Placas de video', NULL, now(), now()),
(86, 'Línea AMD RADEON', 85, now(), now()),
(87, 'Línea Intel Arc', 85, now(), now()),
(88, 'Línea NVIDIA GEFORCE', 85, now(), now()),
(89, 'Línea Quadro/Radeon Pro', 85, now(), now()),
(90, 'Proyectores', NULL, now(), now()),
(91, 'Scanners', NULL, now(), now()),
(92, 'Sillas y escritorios', NULL, now(), now()),
(93, 'Tablets', NULL, now(), now());

SELECT setval('categorias_id_seq', 93, true);
