-- Árbol fijo de categorías (sección > categoría > subcategoría), provisto por el negocio.
-- Los ids son explícitos porque el orden de inserción determina la jerarquía (padre_id
-- referencia el id de la fila insertada justo antes en su nivel superior).
CREATE TABLE categorias (
    id BIGSERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    padre_id BIGINT REFERENCES categorias(id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_categorias_padre ON categorias(padre_id);

INSERT INTO categorias (id, nombre, padre_id, created_at, updated_at) VALUES
(1, 'Componentes', NULL, now(), now()),
(2, 'Almacenamiento', 1, now(), now()),
(3, 'Discos Externos', 2, now(), now()),
(4, 'Discos Externos SSD', 2, now(), now()),
(5, 'Discos Internos', 2, now(), now()),
(6, 'Discos Internos SSD', 2, now(), now()),
(7, 'Memorias Flash', 2, now(), now()),
(8, 'NAS', 2, now(), now()),
(9, 'Pen Drives', 2, now(), now()),
(10, 'Hardware', 1, now(), now()),
(11, 'Coolers', 10, now(), now()),
(12, 'Fuentes', 10, now(), now()),
(13, 'Gabinetes', 10, now(), now()),
(14, 'Motherboards', 10, now(), now()),
(15, 'Placas de Video', 10, now(), now()),
(16, 'Procesadores', 10, now(), now()),
(17, 'Memorias', 1, now(), now()),
(18, 'Memorias Notebook', 17, now(), now()),
(19, 'Memorias PC', 17, now(), now()),
(20, 'Cómputos', NULL, now(), now()),
(21, 'Computadoras', 20, now(), now()),
(22, 'Mini PC', 21, now(), now()),
(23, 'Notebooks Consumo', 21, now(), now()),
(24, 'Notebooks Corporativo', 21, now(), now()),
(25, 'PC de Escritorio', 21, now(), now()),
(26, 'Imagen', 20, now(), now()),
(27, 'Monitores', 26, now(), now()),
(28, 'Pantallas', 26, now(), now()),
(29, 'Proyectores', 26, now(), now()),
(30, 'Impresión', NULL, now(), now()),
(31, 'Imagen', 30, now(), now()),
(32, 'Escaner', 31, now(), now()),
(33, 'Impresoras', 30, now(), now()),
(34, 'Impresoras de Sistema Continuo', 33, now(), now()),
(35, 'Impresoras de Tickets', 33, now(), now()),
(36, 'Impresoras Inkjet', 33, now(), now()),
(37, 'Impresoras Láser', 33, now(), now()),
(38, 'Plotters', 33, now(), now()),
(39, 'Insumos', 30, now(), now()),
(40, 'Botellas de Tinta', 39, now(), now()),
(41, 'Cartuchos de Plotters', 39, now(), now()),
(42, 'Cartuchos de Tinta', 39, now(), now()),
(43, 'Cilindros', 39, now(), now()),
(44, 'Cintas', 39, now(), now()),
(45, 'Rollos', 39, now(), now()),
(46, 'Toners', 39, now(), now()),
(47, 'Otros', NULL, now(), now()),
(48, 'Accesorios', 47, now(), now()),
(49, 'Accesorios Videojuegos', 48, now(), now()),
(50, 'Candados', 48, now(), now()),
(51, 'Repuestos', 48, now(), now()),
(52, 'Audio', 47, now(), now()),
(53, 'Auriculares', 52, now(), now()),
(54, 'Micrófonos', 52, now(), now()),
(55, 'Parlantes', 52, now(), now()),
(56, 'Cables', 47, now(), now()),
(57, 'Cables', 56, now(), now()),
(58, 'Conectividad', 47, now(), now()),
(59, 'Extensores', 58, now(), now()),
(60, 'Hubs', 58, now(), now()),
(61, 'Placas de Red', 58, now(), now()),
(62, 'Routers', 58, now(), now()),
(63, 'Switches', 58, now(), now()),
(64, 'Estuches', 47, now(), now()),
(65, 'Fundas', 64, now(), now()),
(66, 'Maletines', 64, now(), now()),
(67, 'Mochilas', 64, now(), now()),
(68, 'Imagen', 47, now(), now()),
(69, 'Accesorios', 68, now(), now()),
(70, 'Soportes', 68, now(), now()),
(71, 'Impresoras', 47, now(), now()),
(72, 'Trituradora', 71, now(), now()),
(73, 'Muebles', 47, now(), now()),
(74, 'Sillas', 73, now(), now()),
(75, 'Periféricos', 47, now(), now()),
(76, 'Adaptadores', 75, now(), now()),
(77, 'Bases Notebook', 75, now(), now()),
(78, 'Cámaras Web', 75, now(), now()),
(79, 'Joysticks', 75, now(), now()),
(80, 'Kit', 75, now(), now()),
(81, 'Lampara', 75, now(), now()),
(82, 'Mouse Pads', 75, now(), now()),
(83, 'Mouses', 75, now(), now()),
(84, 'Punteros', 75, now(), now()),
(85, 'Teclados', 75, now(), now()),
(86, 'Volantes', 75, now(), now()),
(87, 'Seguridad', 47, now(), now()),
(88, 'Cámaras IP', 87, now(), now()),
(89, 'Cámaras WiFi', 87, now(), now()),
(90, 'Panel Solar', 87, now(), now()),
(91, 'Simuladores', 47, now(), now()),
(92, 'Luces', 91, now(), now()),
(93, 'Unidad de Energía', 47, now(), now()),
(94, 'Baterías', 93, now(), now()),
(95, 'Cargadores Portátiles', 93, now(), now()),
(96, 'Estabilizadores', 93, now(), now()),
(97, 'Placas de Red', 93, now(), now()),
(98, 'Protectores', 93, now(), now()),
(99, 'UPS', 93, now(), now()),
(100, 'Video Juegos', 47, now(), now()),
(101, 'Consolas', 100, now(), now());

SELECT setval('categorias_id_seq', 101, true);

-- El producto se clasifica en una subcategoría (hoja). categoria (texto crudo del mayorista)
-- se mantiene como insumo de la clasificación; ya no se muestra al usuario final.
ALTER TABLE productos ADD COLUMN categoria_id BIGINT REFERENCES categorias(id);
CREATE INDEX idx_productos_categoria ON productos(categoria_id);
